format = """
$python\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "white"

[character]
success_symbol = "[â¯â¯](purple)"
error_symbol = "[â¯â¯](red)"
vimcmd_symbol = "[â®](green)"

[git_branch]
format = "[<$branch>]($style)"
style = "yellow"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[\($virtualenv $symbol\)]($style) '
style = "white"
symbol = "ğŸ"

[username]
show_always = true
format = '[$user]($style)'
style_user = "yellow"

[hostname]
ssh_only = false
format = '@(white)[$hostname$ssh_symbol]($style) '
style = "green bold"
